apiVersion: v1
kind: Service
metadata:
  name: db  #name of what the voter app is set to look for
  labels:
    name: db-service
    app: demo-voting-app

spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app